# Generated by Django 2.2 on 2020-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallPass', '0002_auto_20200226_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='users',
            field=models.ManyToManyField(related_name='celebs', to='HallPass.User'),
        ),
    ]
